### ISSUE TITLE
Upgrading create-pull-request to v3

### ISSUE THREAD

**Issue by kaisugi** [stevemar/image-deleter#1]
First of all, thanks for creating this simple yet convenient action!

When I tried on my personal project, I found some errors on the phase of generating PRs. Actually it's not at all your fault, caused by `create-pull-request@v2` (details are in https://github.com/peter-evans/create-pull-request/issues/632 ). That's why I suggest upgrading it to v3. 
[This documentation](https://github.com/peter-evans/create-pull-request/blob/master/docs/updating.md) would be helpful.

**Comment by stevemar** [comment]
hey @HelloRusk thanks for letting me know you found the project useful. It looks like the upgrade to v3 is pretty simple, i updated the README: https://github.com/stevemar/image-deleter/commit/15b4b12e37d6c66992b6bd3d5be46b0caa4104c9 and tested it out here: https://github.com/stevemar/testing-images/pull/6.

I've also updated my blog post https://www.stevemar.net/github-actions-rm-images/ in case you found this project through there.
